In [1]:
import numpy as np

a = np.random.randn(5)  # "rank 1 array", do not use!

In [2]:
print(a)

[-0.3930157   0.64434363 -1.57372483 -1.63794698 -0.04654036]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.3930157   0.64434363 -1.57372483 -1.63794698 -0.04654036]


In [5]:
print(np.dot(a, a.T))

5.73128621976


In [6]:
a = a.reshape((5, 1))  # convert a "rank 1 array" to a column vector
print(a)

[[-0.3930157 ]
 [ 0.64434363]
 [-1.57372483]
 [-1.63794698]
 [-0.04654036]]


In [7]:
a = np.random.randn(5, 1)  # column vector
print(a)

[[ 0.26598786]
 [ 0.19517614]
 [ 1.86790838]
 [-1.11005558]
 [ 0.75642511]]


In [8]:
print(a.T)  # row vector

[[ 0.26598786  0.19517614  1.86790838 -1.11005558  0.75642511]]


In [9]:
assert(a.shape == (5, 1))